# To change this license header, choose License Headers in Project Properties.
# To change this template file, choose Tools | Templates
# and open the template in the editor.


mutationMap = {
   'ALA': {
        'ALA':'',
        'CYS':'+:SG', 
        'ASP':'+CG,OD1,OD2',
        'GLU':'+CG,CD,OE1,OE2', 
        'PHE':'+CG,CD1,CE1,CZ,CE2,CD2', 
        'GLY':'-CB',
        'HIS':'-CB + CB CG ND1 CE1 NE2 CD2 ',
        'ILE':'-CB',
        'LYS':'-CB',
        'LEU':'-CB +CB CG CD1 CD2  ',
        'MET':'-CB',
        'ASN':'-CB',
        'PRO':'-CB',
        'GLN':'-CB',
        'ARG':'-CB',
        'SER':'-CB +CB OG ',
        'THR':'-CB +CB CG2 OG1',
        'VAL':'-CB',
        'TRP':'-CB',
        'TYR':'-CB'
   },
   'CYS': {
        'ALA':'+CB',
        'CYS':'', 
        'ASP':'',
        'GLU':'', 
        'PHE':'', 
        'GLY':'',
        'HIS':'+CB CG ND1 CE1 NE2 CD2',
        'ILE':'',
        'LYS':'',
        'LEU':'+CB CG CD1 CD2  ',
        'MET':'',
        'ASN':'',
        'PRO':'',
        'GLN':'',
        'ARG':'',
        'SER':'+CB OG',
        'THR':'+CB CG2 OG1',
        'VAL':'',
        'TRP':'',
        'TYR':''
   },
   'ASP':{
        'ALA':'',
        'CYS':'', 
        'ASP':'',
        'GLU':'', 
        'PHE':'', 
        'GLY':'',
        'HIS':'+CB CG ND1 CE1 NE2 CD2',
        'ILE':'',
        'LYS':'',
        'LEU':'+CB CG CD1 CD2  ',
        'MET':'',
        'ASN':'',
        'PRO':'',
        'GLN':'',
        'ARG':'',
        'SER':'+CB OG',
        'THR':'+CB CG2 OG1',
        'VAL':'',
        'TRP':'',
        'TYR':''
   },
   'GLU':{
        'ALA':'+CB',
        'CYS':'', 
        'ASP':'',
        'GLU':'', 
        'PHE':'', 
        'GLY':'',
        'HIS':'+CB CG ND1 CE1 NE2 CD2',
        'ILE':'',
        'LYS':'',
        'LEU':'+CB CG CD1 CD2  ',
        'MET':'',
        'ASN':'',
        'PRO':'',
        'GLN':'',
        'ARG':'',
        'SER':'+CB OG',
        'THR':'+CB CG2 OG1',
        'VAL':'',
        'TRP':'',
        'TYR':''
   },
   'PHE':{
        'ALA':'+CB',
        'CYS':'', 
        'ASP':'',
        'GLU':'', 
        'PHE':'', 
        'GLY':'',
        'HIS':'+CB CG ND1 CE1 NE2 CD2',
        'ILE':'',
        'LYS':'',
        'LEU':'+CB CG CD1 CD2  ',
        'MET':'',
        'ASN':'',
        'PRO':'',
        'GLN':'',
        'ARG':'',
        'SER':'+CB OG',
        'THR':'+CB CG2 OG1',
        'VAL':'',
        'TRP':'',
        'TYR':''
   },
   'GLY':{
        'ALA':'+CB',
        'CYS':'', 
        'ASP':'',
        'GLU':'', 
        'PHE':'', 
        'GLY':'',
        'HIS':'+CB CG ND1 CE1 NE2 CD2',
        'ILE':'',
        'LYS':'',
        'LEU':'+CB CG CD1 CD2  ',
        'MET':'',
        'ASN':'',
        'PRO':'',
        'GLN':'',
        'ARG':'',
        'SER':'+CB OG',
        'THR':'+CB CG2 OG1',
        'VAL':'',
        'TRP':'',
        'TYR':''
   },
   'HIS':{
        'ALA':'-CB CG ND1 CE1 NE2 CD2 +CB',
        'CYS':'-CB CG ND1 CE1 NE2 CD2 ', 
        'ASP':'-CB CG ND1 CE1 NE2 CD2 ',
        'GLU':'-CB CG ND1 CE1 NE2 CD2 ', 
        'PHE':'-CB CG ND1 CE1 NE2 CD2 ', 
        'GLY':'-CB CG ND1 CE1 NE2 CD2 ',
        'HIS':'-CB CG ND1 CE1 NE2 CD2 +CB CG ND1 CE1 NE2 CD2',
        'ILE':'-CB CG ND1 CE1 NE2 CD2 ',
        'LYS':'-CB CG ND1 CE1 NE2 CD2 ',
        'LEU':'-CB CG ND1 CE1 NE2 CD2 +CB CG CD1 CD2  ',
        'MET':'-CB CG ND1 CE1 NE2 CD2 ',
        'ASN':'-CB CG ND1 CE1 NE2 CD2 ',
        'PRO':'-CB CG ND1 CE1 NE2 CD2 ',
        'GLN':'-CB CG ND1 CE1 NE2 CD2 ',
        'ARG':'-CB CG ND1 CE1 NE2 CD2 ',
        'SER':'-CB CG ND1 CE1 NE2 CD2 +CB OG',
        'THR':'-CB CG ND1 CE1 NE2 CD2 +CB CG2 OG1',
        'VAL':'-CB CG ND1 CE1 NE2 CD2 ',
        'TRP':'-CB CG ND1 CE1 NE2 CD2 ',
        'TYR':'-CB CG ND1 CE1 NE2 CD2 '
   },
   'ILE':{
        'ALA':'+CB',
        'CYS':'', 
        'ASP':'',
        'GLU':'', 
        'PHE':'', 
        'GLY':'',
        'HIS':'+CB CG ND1 CE1 NE2 CD2',
        'ILE':'',
        'LYS':'',
        'LEU':'+CB CG CD1 CD2  ',
        'MET':'',
        'ASN':'',
        'PRO':'',
        'GLN':'',
        'ARG':'',
        'SER':'+CB OG',
        'THR':'+CB CG2 OG1',
        'VAL':'',
        'TRP':'',
        'TYR':''
   },
   'LYS':{
        'ALA':'+CB',
        'CYS':'', 
        'ASP':'',
        'GLU':'', 
        'PHE':'', 
        'GLY':'',
        'HIS':'+CB CG ND1 CE1 NE2 CD2',
        'ILE':'',
        'LYS':'',
        'LEU':'+CB CG CD1 CD2  ',
        'MET':'',
        'ASN':'',
        'PRO':'',
        'GLN':'',
        'ARG':'',
        'SER':'+CB OG',
        'THR':'+CB CG2 OG1',
        'VAL':'',
        'TRP':'',
        'TYR':''
   }, 
   'LEU': {
        'ALA':'+CB',
        'CYS':'', 
        'ASP':'',
        'GLU':'', 
        'PHE':'', 
        'GLY':'',
        'HIS':'+CB CG ND1 CE1 NE2 CD2',
        'ILE':'',
        'LYS':'',
        'LEU':'+CB CG CD1 CD2  ',
        'MET':'',
        'ASN':'',
        'PRO':'',
        'GLN':'',
        'ARG':'',
        'SER':'+CB OG',
        'THR':'+CB CG2 OG1',
        'VAL':'',
        'TRP':'',
        'TYR':''
   },
   'MET':{
        'ALA':'+CB',
        'CYS':'', 
        'ASP':'',
        'GLU':'', 
        'PHE':'', 
        'GLY':'',
        'HIS':'+CB CG ND1 CE1 NE2 CD2',
        'ILE':'',
        'LYS':'',
        'LEU':'+CB CG CD1 CD2  ',
        'MET':'',
        'ASN':'',
        'PRO':'',
        'GLN':'',
        'ARG':'',
        'SER':'+CB OG',
        'THR':'+CB CG2 OG1',
        'VAL':'',
        'TRP':'',
        'TYR':''
   },
   'ASN':{
        'ALA':'+CB',
        'CYS':'', 
        'ASP':'',
        'GLU':'', 
        'PHE':'', 
        'GLY':'',
        'HIS':'+CB CG ND1 CE1 NE2 CD2',
        'ILE':'',
        'LYS':'',
        'LEU':'+CB CG CD1 CD2  ',
        'MET':'',
        'ASN':'',
        'PRO':'',
        'GLN':'',
        'ARG':'',
        'SER':'+CB OG',
        'THR':'+CB CG2 OG1',
        'VAL':'',
        'TRP':'',
        'TYR':''
   },
   'PRO':{
        'ALA':'+CB',
        'CYS':'', 
        'ASP':'',
        'GLU':'', 
        'PHE':'', 
        'GLY':'',
        'HIS':'+CB CG ND1 CE1 NE2 CD2',
        'ILE':'',
        'LYS':'',
        'LEU':'+CB CG CD1 CD2  ',
        'MET':'',
        'ASN':'',
        'PRO':'',
        'GLN':'',
        'ARG':'',
        'SER':'+CB OG',
        'THR':'+CB CG2 OG1',
        'VAL':'',
        'TRP':'',
        'TYR':''
   }, 
   'GLN':{
        'ALA':'+CB',
        'CYS':'', 
        'ASP':'',
        'GLU':'', 
        'PHE':'', 
        'GLY':'',
        'HIS':'+CB CG ND1 CE1 NE2 CD2',
        'ILE':'',
        'LYS':'',
        'LEU':'+CB CG CD1 CD2  ',
        'MET':'',
        'ASN':'',
        'PRO':'',
        'GLN':'',
        'ARG':'',
        'SER':'+CB OG',
        'THR':'+CB CG2 OG1',
        'VAL':'',
        'TRP':'',
        'TYR':''
   }, 
   'ARG':{
        'ALA':'+CB',
        'CYS':'', 
        'ASP':'',
        'GLU':'', 
        'PHE':'', 
        'GLY':'',
        'HIS':'+CB CG ND1 CE1 NE2 CD2',
        'ILE':'',
        'LYS':'',
        'LEU':'+CB CG CD1 CD2  ',
        'MET':'',
        'ASN':'',
        'PRO':'',
        'GLN':'',
        'ARG':'',
        'SER':'+CB OG',
        'THR':'+CB CG2 OG1',
        'VAL':'',
        'TRP':'',
        'TYR':''
   },
    'SER':{
        'ALA':'-CB OG+CB',
        'CYS':'-CB OG', 
        'ASP':'-CB OG',
        'GLU':'-CB OG', 
        'PHE':'-CB OG', 
        'GLY':'-CB OG',
        'HIS':'-CB OG+CB CG ND1 CE1 NE2 CD2',
        'ILE':'-CB OG',
        'LYS':'-CB OG',
        'LEU':'-CB OG+CB CG CD1 CD2  ',
        'MET':'-CB OG',
        'ASN':'-CB OG',
        'PRO':'-CB OG',
        'GLN':'-CB OG',
        'ARG':'-CB OG',
        'SER':'+CB OG',
        'THR':'-CB OG+CB CG2 OG1',
        'VAL':'-CB OG',
        'TRP':'-CB OG',
        'TYR':'-CB OG'
   },
   'THR':{
        'ALA':'-CB CG2 OG1+CB',
        'CYS':'-CB CG2 OG1', 
        'ASP':'-CB CG2 OG1',
        'GLU':'-CB CG2 OG1', 
        'PHE':'-CB CG2 OG1', 
        'GLY':'-CB CG2 OG1',
        'HIS':'-CB CG2 OG1+CB CG ND1 CE1 NE2 CD2',
        'ILE':'-CB CG2 OG1',
        'LYS':'-CB CG2 OG1',
        'LEU':'-CB CG2 OG1',
        'MET':'-CB CG2 OG1',
        'ASN':'-CB CG2 OG1',
        'PRO':'-CB CG2 OG1',
        'GLN':'-CB CG2 OG1',
        'ARG':'-CB CG2 OG1',
        'SER':'-CB CG2 OG1+CB OG',
        'THR':'-CB CG2 OG1+CB CG2 OG1',
        'VAL':'-CB CG2 OG1',
        'TRP':'-CB CG2 OG1',
        'TYR':'-CB CG2 OG1'
   },
   'VAL':{
        'ALA':'+CB',
        'CYS':'', 
        'ASP':'',
        'GLU':'', 
        'PHE':'', 
        'GLY':'',
        'HIS':'+CB CG ND1 CE1 NE2 CD2',
        'ILE':'',
        'LYS':'',
        'LEU':'',
        'MET':'',
        'ASN':'',
        'PRO':'',
        'GLN':'',
        'ARG':'',
        'SER':'+CB OG',
        'THR':'+CB CG2 OG1',
        'VAL':'',
        'TRP':'',
        'TYR':''
   },
   'TRP':{
        'ALA':'+CB',
        'CYS':'', 
        'ASP':'',
        'GLU':'', 
        'PHE':'', 
        'GLY':'',
        'HIS':'+CB CG ND1 CE1 NE2 CD2',
        'ILE':'',
        'LYS':'',
        'LEU':'',
        'MET':'',
        'ASN':'',
        'PRO':'',
        'GLN':'',
        'ARG':'',
        'SER':'+CB OG',
        'THR':'+CB CG2 OG1',
        'VAL':'',
        'TRP':'',
        'TYR':''
   }, 
   'TYR':{
        'ALA':'+CB',
        'CYS':'', 
        'ASP':'',
        'GLU':'', 
        'PHE':'', 
        'GLY':'',
        'HIS':'+CB CG ND1 CE1 NE2 CD2',
        'ILE':'',
        'LYS':'',
        'LEU':'',
        'MET':'',
        'ASN':'',
        'PRO':'',
        'GLN':'',
        'ARG':'',
        'SER':'',
        'THR':'+CB CG2 OG1',
        'VAL':'',
        'TRP':'',
        'TYR':''
   },
}
